git:
  submodules: false
language: scala
sudo: required
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - device-tree-compiler
      - libusb-1.0-0-dev
- python-pexpect


jobs:
  include:
    - &test
      stage: Test
      script:
        - ./build-setup.sh
